export const newRegistrationInputs = [
  {
    label: "Contact Number",
    id: "contactNumber",
    type: "text",
    width: "w-7/12",
    placeholder: "Contact Number",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "Registration Number",
    id: "regNumber",
    type: "text",
    width: "w-full",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "Department (with specialisation)",
    id: "department",
    type: "text",
    width: "w-full",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "Year of graduation",
    id: "year",
    type: "text",
    width: "w-4/12",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "College email-id",
    id: "email",
    type: "email",
    width: "w-7/12",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "Where did you hear about the event",
    id: "info",
    type: "text",
    width: "w-7/12",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
];

export const newQueriesInput = [
  {
    label: "Doubts",
    id: "doubt",
    type: "text",
    width: "w-full",
    placeholder: "",
    required: true,
    description: "doubts",
  },
  {
    label: "E - mail",
    id: "email",
    type: "email",
    width: "w-full",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
];

export const newFeedbackInput = [
  {
    label: "Thoughts on the event",
    id: "thoughts",
    type: "text",
    width: "w-full",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "Recommendations",
    id: "recommendations",
    type: "text",
    width: "w-full",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "Experience gained from the event",
    id: "experience",
    type: "text",
    width: "w-full",
    placeholder: "",
    required: true,
    description: "As per your ID card",
  },
];

export const newNameInput = [
  {
    label: "First Name",
    id: "firstName",
    type: "text",
    width: "w-[47%]",
    placeholder: "First Name",
    required: true,
    description: "As per your ID card",
  },
  {
    label: "Last Name",
    id: "lastName",
    type: "text",
    width: "w-[47%]",
    placeholder: "Last Name",
    required: true,
    description: "As per your ID card",
  },
];
